anime_mode=on
fidelity_4K=true
fidelity_8K=true
fidelity_FHD=false
fidelity_SD=false
fidelity_HD=true
fidelity_2K=true
sd_mode=clean
sd_override=false
hd_override=false
shaders_enabled=true
sharpen_enabled=true
spatial_active=false
upmix_active=false
night_mode_active=false
up_next_enabled=true
skip_intro_enabled=true
history_enabled=true
line_thinner_enabled=true
track_selector_enabled=true
